FROM alpine:latest
WORKDIR /pb
# Download PocketBase
ARG PB_VERSION=0.22.4
RUN apk add --no-cache wget unzip && \
    wget https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip && \
    unzip pocketbase_${PB_VERSION}_linux_amd64.zip -d /pb && \
    rm pocketbase_${PB_VERSION}_linux_amd64.zip

COPY pb_migrations /pb/pb_migrations
EXPOSE 8090

# Persistent data lives in /pb/pb_data (mounted as Render disk)
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090", "--dir=/pb/pb_data"]



